### ISSUE TITLE
GCP: Access

### ISSUE THREAD

**Issue by b300098957** [CollegeBoreal/INF1087-200-20H-02#1]
problème avec les comptes GCP. Courriel de GCP Education envoyé faire suivi avec élèves

**Comment by b300098957** [comment]
Confirmation à date

- [x] Abdelkader

- [ ] Cheick 

- [ ] Olaitan

**Comment by AEKchaouche** [comment]
Je utilise mon compte personnel, j’ai activer ma Platform Google Cloud avec le  Coupon Code

**Comment by b300098957** [comment]
Merci @AEKchaouche

**Comment by b300098957** [comment]
[Accès](https://github.com/CollegeBoreal/20H/blob/master/GINQ.md) Résolu
